### ISSUE TITLE
Autosync not starting

### ISSUE THREAD

**Issue by warp10** [Odoo-mobile/framework#142] opened 2016-04-18 10:06 UTC
Hi there,

I have a small application built around the odoo mobile addons tutorial. It works quite good, as I am able to sync project.task bidirectionally with a swipe. Tasks created on Android are shown on Odoo, and the other way round too.

The issue I'm facing is about autosync. I am under a wifi network, with syncs enabled every 5 minutes for objects up to 12 months, yet the sync never actually starts. I don't get any error in the Android Monitor on Android Studio, actually nothing is shown at all, as if the sync process is actually never run by Android. Nevertheless, the sync task is enabled on Android (as you can see from the attached screenshot), and if I manually disable and then re-enable it there, the sync goes great.

Anybody has an idea of what's wrong?

![device-2016-04-18-120213](https://cloud.githubusercontent.com/assets/855966/14600533/6aa03426-055d-11e6-9ef1-529cc65b15d2.png)
![device-2016-04-18-120201](https://cloud.githubusercontent.com/assets/855966/14600534/6aa72100-055d-11e6-992b-5d3c46388e0d.png)

**Comment by 74n3r** [comment] 2016-04-26 11:49
i have some problems.. also i can see only odoo's menus . himself nothing..

**Comment by YPerezM** [comment] 2016-05-05 08:00
I have a problem with the sync between device and server. Any change that I make on my device doesnt appear on the server(for example, a new customer), and vice versa. The problem is that in my Settings-->Accounts-->Odoo I cant sync anything, nothing appear. I didnt find any solution to this.

Screenshot from device:
![screenshot_2016-05-05-09-50-44](https://cloud.githubusercontent.com/assets/8902208/15038869/16721ca4-12a8-11e6-83e6-34ffadff12bd.png)

**Comment by mikedream89** [comment] 2016-05-13 02:08
@YPerezM 
I add the line android:isAlwaysSyncable="true" in customer_sync_adapter.xml , but it not autosync ?
why?

**Comment by YPerezM** [comment] 2016-05-13 10:08
@mikedream89 
And do you check your Manifest? You have to change android:authorities="${applicationId}.core.provider.content.sync.res_partner" to android:authorities="com.odoo.core.provider.content.sync.res_partner". 
It should work fine with these changes

**Comment by 74n3r** [comment] 2016-05-13 12:17
..or  android:authorities="com.odoo.core.provider.res_partner"  @mikedream89 @YPerezM

**Comment by kasim1011** [comment] 2016-05-17 10:44
Hey, Does your emulator or phone running lower version than **Kitkat** than you should see [this](https://github.com/Odoo-mobile/framework/issues/165#issuecomment-219676006).

**Comment by warp10** [comment] 2016-05-20 08:56
Hey @YPerezM thanks a lot for your information. Days after I reported this issue I found out that the sync actually starts, despite being run at quite random time, totally ignoring the settings the user choose. Nevertheless, I will implement your tuning and see if things change a little bit.

@kasim1011 Good to know, thanks!

**Comment by raulalejandromm** [comment] 2016-06-22 16:01
Buenas.. disculpe. de mi parte no tengo el archivo customer_sync_adapter.xml

**Comment by dpr-odoo** [comment] 2016-11-15 06:44
Similar issue will be fixed in #165

**Closed by dpr-odoo** 2016-11-15 06:44 UTC
