### ISSUE TITLE
how to add multiple domain to single OColumn in odoo mobile framework

### ISSUE THREAD

**Issue by amar-teckzilla** [Odoo-mobile/framework#268] opened 2016-11-22 08:05 UTC
I am trying add domain to Ocolumn in Omodel.I am able to add domain when it has boolean field for eg ("isbool","=","true")

<field name="categ_id" required = "1"/>
 <field name="product_type" required = "1"/>	
<field name="product_id" domain="[('product_type', '=',product_type),('categ_id', '=',categ_id)]"/>

                  how do i add domain to above example???

**Comment by dpr-odoo** [comment] 2016-11-22 09:09
Hello,

You can add domain by calling chain methods for example
``[("isbool","=",true), ("isactive","=", true), ("state","=","draft")]`` is like

```java
OColumn ref_id = new OColumn("Reference", RefereneTable.class, RelationType.ManyToOne)
            .addDomain("isbool","=",true).addDomain("and")
            .addDomain("isactive","=",true).addDomain("or")
            .addDomain("state","=","draft");
```

**Comment by adam-nadar** [comment] 2016-11-22 10:12
Thanks for the reply. But, our scenario is different. We want to add domain for dependent fields. Below is the example from XML which we have used in the odoo.
Value of product_id is dependent on categ_id and product_type fields
<field name="categ_id" required = "1"/>
 <field name="product_type" required = "1"/> 
<field name="product_id" domain="[('product_type', '=',product_type),('categ_id', '=',categ_id)]"/>

**Comment by amar-teckzilla** [comment] 2016-11-23 14:24
Can we get the kindy get reply ,as we  got stuck in a project where we need to enter the domain on Ocolumn

**Comment by dpr-odoo** [comment] 2016-11-24 05:35
@amar-teckzilla @adam-nadar 

I think you need to update particular field value depending on the another field's value but currently ``OColumn`` not support for dynamic domain based on another field value change. 

What it does, is just filtering data when ``OForm`` initialize  

Marking it as **improvement** for *dependent fields value change handling* and it available soon.

**Comment by amar-teckzilla** [comment] 2016-11-24 05:42
Thanks for the reply..

**Comment by adam-nadar** [comment] 2016-11-30 09:57
is it possible to create a field like
OColumn country =new OColumn("your country",OSelection.class).addSelection("a","A").addSelection("b","B")

OColumn state=new OColumn("your state",OSelection.class).addSelection("x","X").addSelection("y","Y")

on selection of country field can we filter the state fields options???

**Comment by dpr-odoo** [comment] 2016-11-30 10:15
@adam-nadar Not now. I'm working on this. It will available soon.

**Comment by adam-nadar** [comment] 2016-11-30 14:12
il tis workin my case?

![img_30112016_194150](https://cloud.githubusercontent.com/assets/20593541/20755469/205c6a8a-b735-11e6-9595-396a76d16876.png)

**Comment by adam-nadar** [comment] 2016-12-02 08:11
@dpr-odoo **the app crashes wen I try to add new Customer (FAB onClick)**
12-02 12:40:49.450 10091-10091/com.field E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.field, PID: 10091
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.field/com.odoo.addons.customers.CustomerDetails}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.odoo.core.orm.ODataRow.get(java.lang.String)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.odoo.core.orm.ODataRow.get(java.lang.String)' on a null object reference
at odoo.controls.OForm.getControlValues(OForm.java:228)
at odoo.controls.OSelectionField.createItems(OSelectionField.java:280)
at odoo.controls.OSelectionField.initControl(OSelectionField.java:149)
at odoo.controls.OSelectionField.setWidgetType(OSelectionField.java:464)
at odoo.controls.OField.initSelectionWidget(OField.java:436)
at odoo.controls.OField.initControl(OField.java:260)
at odoo.controls.OForm.initForm(OForm.java:172)
at odoo.controls.OForm.initForm(OForm.java:140)
at com.odoo.addons.customers.CustomerDetails.setupToolbar(CustomerDetails.java:146)
at com.odoo.addons.customers.CustomerDetails.onCreate(CustomerDetails.java:104)

**after selecting the country field state can b selected
if the operation is reversed then it crashes**

12-02 12:50:16.688 16816-16816/com.field E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.field, PID: 16816
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.field/odoo.controls.SearchableItemActivity}: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
at com.odoo.core.orm.fields.utils.DomainFilterParser.getRPCDomain(DomainFilterParser.java:160)
at odoo.controls.SearchableItemActivity.onCreate(SearchableItemActivity.java:115)
at android.app.Activity.performCreate(Activity.java:6259)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
at android.app.ActivityThread.-wrap11(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:148) 
at android.app.ActivityThread.main(ActivityThread.java:5443) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by dpr-odoo** [comment] 2016-12-05 05:25
Hello @adam-nadar 

Some of the improvement done for dynamic domain apply to field in ``OForm`` 

Before update: ``@Odoo.hasDomainFilter`` not working properly 
In new update: ~~@Odoo.hasDomaiFilter~~ replaced with ``@Odoo.Domain()``

**Syntax:**

```java
@Odoo.Domain("[['country_id', '=', @country_id]]")
OColumn state_id = new OColumn("State", ResCountryState.class, OColumn.RelationType.ManyToOne);
OColumn country_id = new OColumn("Country", ResCountry.class, OColumn.RelationType.ManyToOne);
```

You can see the new changed syntax for Domain filter: 
```java
@Odoo.Domain("[['country_id', '=', @country_id]]")
```

It will apply dynamic value to ``state_id`` when ``country_id`` value changed. It will take infix formatted domain covered with ``[]`` array square brackets. Each of the domain will be added inside ``[]`` with 3 values

1. column name of the related table (i.e, ``country_id`` field of ``res.country.state`` model)
2. condition operator (valid condition operator = != < > ....)
3. Field name of the current model on which field is dependent, in this example ``state_id`` is dependent on ``country_id`` so just pass ``@`` before field name and put directly it like ``@country_id``. It will be replaced with dynamic value from ``OForm`` 

For multiple domains, you can put like:

```java
@Odoo.Domain("[['country_id', '=', @country_id], 'and', ['active', '=', true]]")
```

Rest of the work will be done automatically in all cases, If you are using DropDown or SearchableLive Activity. 

Domain (infix) will be automatically converted to **Odoo** format (prefix) domain in searchable live items.

Please check the update (https://github.com/Odoo-mobile/framework/tree/master-depend-domain-field-dpr) with your issues, and let me know if it has any bug or not so I can merge it to main branch. 

Thanks.

**Comment by adam-nadar** [comment] 2016-12-06 06:22
@dpr-odoo we made all the fields to be static as OSelection field coz we were in  tight schedule 

as for testing part we jst tried wit res.partners fields state and country and it looks good..
thank you for the update

**Closed** 2016-12-07 06:27 UTC
Labels: improvement, ★★★

**Comment by adam-nadar** [comment] 2016-12-08 12:26
@dpr-odoo in my case 
like country is OSelection field and state is Many2one field 
so when I 
`<odoo.controls.OField
        android:layout_width="match_parent"
        app:widgetType="SearchableLive"
        android:layout_height="wrap_content"
        app:fieldName="product_type" />
    <odoo.controls.OField
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:widgetType="SearchableLive"
        app:fieldName="categ_id"/>`
use it
it crashes
as `
OColumn product_type = new OColumn("Product Type", OSelection.class)
            .addSelection("equipment","Equipment")
            .addSelection("consumable", "Consumable");
@Odoo.Domain("[['product_type_new', '=', @product_type]]")
    OColumn categ_id=new OColumn("Category",ProductCategory.class, OColumn.RelationType.ManyToOne);`

`Process: com.appasamy, PID: 9969
                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
                                                                at com.odoo.core.orm.ODataRow.getInt(ODataRow.java:46)
                                                                at odoo.controls.OField.onValueUpdate(OField.java:534)
                                                                at odoo.controls.OSelectionField.setValue(OSelectionField.java:423)
                                                                at odoo.controls.OSelectionField.onItemSelected(OSelectionField.java:539)
                                                                at android.widget.AdapterView.fireOnSelected(AdapterView.java:931)`
